### ISSUE TITLE
Could bulk_load accept an iterator?

### ISSUE THREAD

**Issue by IamTheCarl** [georust/rstar#51]
I have a bit of a unique use case where the physical locations of the objects I'm putting in my tree frequently change.
Thanks to your very good documentation, I figured that the time needed to remove, modify, and then re-insert all the objects that changed would be O(n * log(n)). That doesn't seem very practical.

So my next choice is to instead build a new tree on every cycle. My data is not stored in a vector, so I must first construct a vector and then feed it into the tree. That becomes O(n + log(n)). That's a lot better but I still think there's room for improvement.

Would it be possible to to make bulk_load accept any iterator to supply it with objects?
If that's not possible, could it be modified to just borrow the vector, rather than consume it? That would at least save me some time on the memory allocation.

Or maybe there's an easier solution to this problem that I somehow missed?

**Comment by Bauxitedev** [comment]
Seconding this. In my program I'm doing some basic N Body simulation, using rtrees to quickly find the nearest body of another body. Since the bodies move around the tree needs to be created from scratch every frame. But since the bodies are stored in a vector somewhere, using bulk_load() means I need to copy the entire vector every frame, since bulk_load(v) takes ownership of v. If bull_load borrowed v instead that would be a huge help.

**Comment by rmanoka** [comment]
The `bulk_load` source refers to the OMT algorithm designed in [this paper by Lee and Lee (2003)](http://ceur-ws.org/Vol-74/files/FORUM_18.pdf).  I'm not an expert but the algorithm seems to require random-access to the items to be loaded and hence precluding the use of iterators.

Further, the algo needs to re-arrange the list of items as per their geom. coordinates (in a recursive fashion) before inserting into the tree, so it is not possible to use an `&Vec<T>` or `&[T]` for that purpose.

**Comment by Stoeoef** [comment]
@rmanoka is correct unfortunately - the choice of `Vec<T>` is done out of necessity, I'd much rather have `IntoIterator<Item=T>` which would be the idiomatic way to do this.
The reason is that the `Vec` is being sorted (which requires a &mut [T]) and then split into smaller parts via `Vec.split_off` (which requires `Vec<T>`).

Changing the signature to anything else would require to convert the data into a `Vec` anyway.

> So my next choice is to instead build a new tree on every cycle.

@IamTheCarl : This _may_ suggest that RTrees aren't the best data structure for your use case. The major advantage of RTrees is that they allow dynamic, on the fly insertion _even after initial creation_. From what I've read, most other data structures (e.g. k-d trees) have better bulk load performance but are harder to balance after creation compared to r-trees.

I'll close this issue as I think this answer addresses the original question. Please still feel free to reply to this thread if you have further questions!

**Comment by IamTheCarl** [comment]
Thank you.
Yes, I did come to the conclusion in the end that a different data structure was a better fit for my use case.
Still, this is an excellent library, and the speed it gave me blew the doors off all the other experiments my co-workers had done, even with the slowness of rebuilding the tree.
