### ISSUE TITLE
Helping with maintaining the crate

### ISSUE THREAD

**Issue by rmanoka** [georust/rstar#55]
Thanks for the wonderful crate.  As downstream users of this crate, some of the maintainers of the [georust](//github.com/georust) organization (incl. me) wanted to check if you need a hand with the maintenance of this crate.  We should be able to do our best with keeping the deps. up-to-date, esp. with yanked / vulnerable ones, but hopefully also help with improving the efficiency / adding useful functionalities to the crate.

If you are up for it, we would also be very happy to add this crate to the georust organization (which I believe you are already a part of) and make you the main author / admin, along with a couple of maintainers to help with keeping the crate updated.  Otherwise, if you wish to keep the crate as is, you may add a couple of us as maintainers here to help you (pls. see cc-ed contacts below).  Happy to help and apologies if the request sounds overbearing as that is definitely not the intention.

cc: @michaelkirk @urschrei

**Comment by Stoeoef** [comment]
Thanks for reaching out!

I'm definitely not up to standards in regards to maintenance and would welcome if this crate could still be maintained and kept in a good shape!
I would welcome an inclusion into the georust organization and think it's a nice fit.
Unfortunately, I can't really promise any help with that. rstar has always been just a hobby project of mine for which finding motivation to work on became really hard once software development became my day job. But enough of that, I'll look into the mandatory steps that are involved in moving a repository.

Thanks again. This would mean a lot to me and hopefully also help all other downstream users.

**Comment by Stoeoef** [comment]
I have initiated the transfer and given the core team access to the repository. I think someone of georust needs to approve of these changes?
Other than that I'm unsure how you handle uploads to crates.io . Please let me know if you have an idea on how to handle that.

**Comment by michaelkirk** [comment]
Thanks @Stoeoef!

> I'm definitely not up to standards in regards to maintenance and would welcome if this crate could still be maintained and kept in a good shape!
> ...
> Unfortunately, I can't really promise any help with that. rstar has always been just a hobby project of mine for which finding motivation to work on became really hard once software development became my day job.

Even though rstar started as a hobby project for you, lots of people's work (including mine) now depends on it. So, firstly, thank you and congratulations on picking useful hobbies. =)

It's totally normal that circumstances change and that you might not have time nor energy. Sometimes it's temporary, sometimes it's permanent. I hope that one of the values that the georust community provides is an amount of resilience to the ebb and flow of "real life".

anyway, down to business:

> I have initiated the transfer and given the core team access to the repository. I think someone of georust needs to approve of these changes?

Looks like someone has accepted. Welcome to your new home `georust/rstar`!

> Other than that I'm unsure how you handle uploads to crates.io . Please let me know if you have an idea on how to handle that.

If you're not planning on actively doing releases, my preference is that you add 1 or 2 active user owners to crates.io I'm willing and available to do releases, but I confess I might not be the best fit since, as of yet, I've done very little work with the rstar internals. I'm just a user. 
```
cd rstar
cargo owner --add michaelkirk
```
There are likely other folks willing/available who are more familiar with the crate - I'll leave it to them to volunteer.

Additionally, we always have a "team" owner for our crates. To that end, I've created the @georust/rstar-publishers team, you can add it like this:
```
cd rstar
cargo owner --add github:georust:rstar-publishers
```
See https://github.com/georust/meta/blob/master/GUIDELINES.md#crate-publishing-teams for the rationale of team/owners if you're aren't familiar.

Feel free to ask any questions!

**Comment by rmanoka** [comment]
Thanks @Stoeoef for accepting our offer!  will do our best to help you keep this crate up-to-date.

@michaelkirk Thanks for doing the ground work and creating the `rstar-publishers` team.   Pls. feel free to add me to the group;  I hope to provide a helping hand, and have a reasonable understanding of the algo. / heuristics used in the crate.

**Comment by urschrei** [comment]
>  Pls. feel free to add me to the group

Done!

**Comment by Stoeoef** [comment]
> $ cargo owner --add github:georust:rstar-publishers
    Updating crates.io index
error: failed to invite owners to crate rstar: api errors (status 200 OK): only members of a team can add it as an owner

I guess I need to be part of that group to be able to join. I have requested that access. In the meantime, I've added you (@urschrei  @rmanoka ) to the owner list, so you should be able to run that command on your own if you want to.

**Comment by michaelkirk** [comment]
> I guess I need to be part of that group to be able to join. I have requested that access.

Approved!

**Comment by urschrei** [comment]
No worries – my ownership assignment worked and rstar-publishers is now an owner.

**Comment by michaelkirk** [comment]
I think this issue can be closed now. Thank you @Stoeoef!
